### ISSUE TITLE
Maps not working

### ISSUE THREAD

**Issue by Ordo-S** [Ordo-S/jeskaiBeta#13]
in the event.swift model the maps locations are not working.  The issues is that to call the map kit it has a asynchronous call to get location so the return value is being returned before the value is retrieved. 

For example 

- call calculateLat()
- executes call to get location 
- returns value before location is got 

I need to add a completion handler to this code to wait for the location before returning, but I'm not to sure how to do that and have been trying for some time now.  

```swift
func calculateLat() -> CLLocationDegrees{
        var lat: CLLocationDegrees?
        let geocoder = CLGeocoder()
        geocoder.geocodeAddressString(address) {
            placemarks, error in
            let placemark = placemarks?.first
            lat = (placemark?.location?.coordinate.latitude)!
           // need to wait for location to be received 
        }
        return lat!
    }
```
Its pushed to the most current version of dev, will be working on this more tomorrow

**Comment by MarkeyMarke** [comment]
Can I get some instructions on how to reproduce the bug? Also, what's the expected result of the bug when I perform it?

**Comment by Ordo-S** [comment]
Yeah so build the app and run it
Create a event
input a address like

2575 Las Palmas way, San Jose, CA 95133

And then when you save a event that's when it it will crash because it
unwraps nil

**Comment by MarkeyMarke** [comment]
As of today fixed using a completion handler with closure syntax
