### ISSUE TITLE
Keyboard not launching

### ISSUE THREAD

**Issue by Ordo-S** [Ordo-S/jeskaiBeta#6]
On the main storyboard the keyboard will not open with the textview. I think its a issue with xcode4 not working with my assigning the view delegate to the text input but im not sure 
<img width="583" alt="screen shot 2018-11-07 at 11 53 22 am" src="https://user-images.githubusercontent.com/25372795/48157159-c2b47680-e283-11e8-8833-01dfc98a68dd.png">

**Comment by Ordo-S** [comment]
issue is on MattKit branch btw

**Comment by MarkeyMarke** [comment]
Is this on your own project entirely or is this after building on my project?

**Comment by Ordo-S** [comment]
Own project, I nuked what i was working on due to its spagetti nature and it just being a hot mess

**Comment by Ordo-S** [comment]
Okay so its fixed 
I had to change 
`class ViewController: UIViewController, UITextFieldDelegate` to `class ViewController: UIViewController, UITextFieldDelegate`

and then the self was just reworked to 
`eventTextField.delegate = self`
